### ISSUE TITLE
explosion potion

### ISSUE THREAD

**Issue by andrtechno** [polserver/ClassicDistro#9] opened 2022-03-28 19:46 UTC
when using an explosion in a stack, the entire stack explodes

**Comment by Admin-Yukiko** [comment] 2022-03-28 22:31
I do not know if this is unusual behaviour. I don't consider this a bug. Explosion potions are supposed to be "thrown", I believe, as a single item. Plus, in real life, if I activate a grenade and throw it in a box of other explosives, it would most likely cause the box of explosives to explode. If you want to change this behaviour, in the explosion potion use script, check the amount property of the potion and if( potion.amount > 1 ) then prevent the use of the potion. 

I decided a while ago that my participation with updates to the Classic Distro would be "maintenance" updates. I define maintenance updates to mean bug fixes only. I will attempt to fix some bugs. I do not promise I will fix all bugs reported. The Distros, both the Classic and the Modern are community projects. Thus I hope the other members of the POL community would offer their assistance as well.

**Comment by andrtechno** [comment] 2022-03-28 23:32
the same situation with the strength potion. I don't think this is normal, it might be the same with other bottles

Are you the only one who does classic-dist?

**Comment by CWO333** [comment] 2022-03-29 00:50
I think the bug is that they're stackable in the first place. Potions on my shard weren't stackable and the script on my shard looks to be an almost exact duplicate of the classic distro script.

**Comment by DavidJSGardner** [comment] 2022-03-29 06:31
The newer clients set the generic (or stackable) flag on the standard potion items.

The consumption of stacked potions should be addressed in the following two commits:
- [64cdc74](https://github.com/polserver/ClassicDistro/commit/64cdc742867b01571c65ec3e864e5c9dc4f9f90f)
- [5a2b7bc](https://github.com/polserver/ClassicDistro/commit/5a2b7bc18f99bf41541833ae641453111028f385)

**Closed** 2022-03-29 08:03 UTC
